development:
  adapter: async

test:
  adapter: test

production:
  adapter: postgresql
  url: <%= ENV['DATABASE_URL'] %>
  channel_prefix: ramcal_production
  # adapter: redis
  # url: <%= ENV.fetch("REDISCLOUD_URL") { "redis://localhost:6379/1" } %>
  # channel_prefix: container-yard_production
